#!/usr/bin/env python3

from sys import argv
from math import sqrt


def read_test_file(file_name):
    """Function to read numbers from file: one on each line"""

    with open(file_name, "r", encoding="utf-8") as file:
        lines = file.readlines()

    number_to_factor = []

    for line in lines:
        number_to_factor.append(int(line))

    return number_to_factor

def find_numbers(n):
    """Function to find factors of current number"""

    factors = []
    for i in range(2, int(sqrt(n)) + 1):
        while n % i == 0:
            factors.append(i)
            n //= i
    if n > 1:
        factors.append(n)

    factors_str = '*'.join(str(factor) for factor in factors)
    print("{}={}".format(n, factors_str))

def factors(ls):
    """Function to iterate between numbers in file"""

    for i in ls:
        find_numbers(i)

if len(argv) == 3:  # Adjusted index to argv[2]
    factors(read_test_file(argv[2]))  # Corrected index from argv[1] to argv[2]
 
